app:
  name: "test"
  debug: true
server:
  http:
    host: 127.0.0.1
    port: 7801
    ssl: false

logger:
  default:
    level: "debug"
    format: "console"
    isSave: false
    disableCaller: true
    logFileConfig:
      filename: "./out.log"
      maxSize: 20
      maxBackups: 50
      maxAge: 15
      isCompression: true
  test:
    level: "test"
    format: "console"
    isSave: false
    disableCaller: true
    logFileConfig:
      filename: "test.log"
      maxSize: 20
      maxBackups: 50
      maxAge: 15
      isCompression: true
