app:
  name: test
  debug: true


server:
  http:
    host:
    port: 7101
    ssl: false
  ext: >-
    {      
    } 

logger:
  default:
    level: "debug"
    format: "console"
    isSave: false
    logFileConfig:
      filename: "./out.log"

redis:
  dsn: "vincent:qt%402023@127.0.0.1:6379/0"
  dialTimeout: 10
  readTimeout: 2
  writeTimeout: 2
  queueConfig:
    stream: "order_events"
    group: "order_processing_group"
    dlqStream: "order_dlq"
    maxRetries: 3
    consumerName: "consumer-"
    blockTimeout: 5
    pendingCheckInterval: 5
    maxPendingAge: 30

database:
  mysql:
    dev:
      dsn: "root:rootpassword@(127.0.0.1:3306)/dev?parseTime=true&loc=Local&charset=utf8,utf8mb4&useSSL=false"
      enableLog: true
      logLevel: debug
      logger: mysql,default
      cacheType: memory
      maxIdleConns: 10
      maxOpenConns: 100
      connMaxLifetime: 30



