app:
  name: "test"
  debug: true
server:
  http:
    host: 127.0.0.1
    port: 7801
    ssl: false

logger:
  home: "./logs"
  level: "debug"
  format: "console"
  isSave: false
  logFileConfig:
    filename: "out.log"
    maxSize: 20
    maxBackups: 50
    maxAge: 15
    isCompression: true